//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARVpr7.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int id { get; set; }
        public int id_book { get; set; }
        public int id_reader { get; set; }
        public System.DateTime planned_date_of_issue { get; set; }
        public System.DateTime actual_date_of_issue { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
